### ISSUE TITLE
All links and buttons broken 

### ISSUE THREAD

**Issue by PickledPunk** [Lattyware/manydecks#24] opened 2020-11-05 23:14 UTC
I tried using Many Decks, but was unable to navigate the page. The only things I can click on are the language, the Sign In button, and I can physically type in the search bar, however the actual search function does not work. Even after going to Sign In, both options to sign in with Google or Twitch do not work. I can click the buttons, but it remains on that page.

**Comment by Lattyware** [comment] 2020-11-06 00:02
Hrm, this may have been a temporary glitch while the server was down for an automatic update or something, I can't reproduce these issues. I've just successfully signed in with Google and Twitch and everything appears to be working. Can you let me know if this problem is persisting or if things are working for you now?

**Comment by Lattyware** [comment] 2020-11-18 16:09
I'm going to close this as I can't reproduce it, and no one has said they've encountered it again.

If anyone does have this problem again, please just open a new issue for it, thanks.

**Closed by Lattyware** 2020-11-18 16:09 UTC
Labels: bug
