### ISSUE TITLE
When I log in, there's just red screen showing "Server rejected that"

### ISSUE THREAD

**Issue by L125K0** [Lattyware/manydecks#2] opened 2020-05-21 17:15 UTC
Screenshot
![Zrzut ekranu 2020-05-21 o 19 14 43](https://user-images.githubusercontent.com/65603307/82586131-60864280-9b97-11ea-811f-4e4c32684657.png)

**Comment by Lattyware** [comment] 2020-05-21 18:36
Just want to check, did you close the issue because you stopped getting the error?

**Comment by Lattyware** [comment] 2020-05-21 18:43
I assume closing was a mistake because I saw this too. I think the issue is the token from logging in has expired and the client is showing that error rather than clearing it and taking you back to log in.

I'll try to fix ASAP. For now, you can hack around this by clearing local storage for the site. You can do that in most browsers by clicking the padlock icon next to the URL and choosing an option to do with clearing cookies or site data.

**Comment by Lattyware** [comment] 2020-05-22 04:23
This should now be resolved, please re-open this issue or create a new one if there are any further issues.

**Closed by Lattyware** 2020-05-22 04:23 UTC
